format = "$directory$git_branch$git_status$character"
add_newline = false
palette = "nord"

[directory]
style = "bg:frost fg:polar_night"
format = "[](frost)[ $path ]($style)[](frost) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:aurora_blue fg:polar_night"
format = "[](aurora_blue)[ $symbol$branch ]($style)[](aurora_blue) "

[git_status]
style = "bg:aurora_yellow fg:polar_night"
format = "[](aurora_yellow)[ $all_status$ahead_behind ]($style)[](aurora_yellow) "

[character]
success_symbol = "[❯](bold frost) "
error_symbol = "[❯](bold aurora_red) "

[palettes.nord]
frost = "#88C0D0"
polar_night = "#2E3440"
aurora_blue = "#81A1C1"
aurora_yellow = "#EBCB8B"
aurora_red = "#BF616A"
