format = "[](frost)$os$username$directory$git_branch$git_status$character[](frost) "
add_newline = true
palette = "nord"

[os]
disabled = false
style = "bold bg:frost fg:polar_night"
format = "[ $symbol ]($style)"

[os.symbols]
Debian = "󰣚"
Ubuntu = "󰕈"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:frost fg:polar_night"
style_root = "bg:frost fg:aurora_red"
format = "[$user]($style)"

[directory]
style = "bg:frost fg:polar_night"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:frost fg:polar_night"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:frost fg:aurora_red"
format = "[$all_status$ahead_behind ]($style)"

[character]
format = "$symbol"
success_symbol = "[❯ ](bold bg:frost fg:polar_night)"
error_symbol = "[❯ ](bold bg:frost fg:aurora_red)"

[palettes.nord]
frost = "#88C0D0"
polar_night = "#2E3440"
aurora_red = "#BF616A"
