# ============================================================
# MPV keybindings
# ============================================================


# Debanding
d cycle deband

# Audio track
a cycle audio

# Subtitle track
s cycle sub

# Legenda maior / menor
CTRL++ add sub-scale 0.05
CTRL+- add sub-scale -0.05

# Legenda para cima / baixo
ALT+UP add sub-pos -1
ALT+DOWN add sub-pos 1

# Screenshot
S screenshot

# Frame por frame
. frame-step
, frame-back-step

# Volume
UP add volume 5
DOWN add volume -5

# Seek
RIGHT seek 5
LEFT seek -5

# Seek maior
SHIFT+RIGHT seek 30
SHIFT+LEFT seek -30
